services:
  db:
    image: mysql:8
    container_name: justBuild.it_mysql_db
    volumes:
      - db_data:/var/justBuild.it/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secretRootPassword
      MYSQL_DATABASE: justBuild.it
      MYSQL_USER: appUser
      MYSQL_PASSWORD: appSecretPassword
    ports:
      - "3306:3306"

volumes:
  db_data: